# Generated by Django 3.1.5 on 2021-07-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_tv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='sd',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='sd_volume_max',
        ),
        migrations.AlterField(
            model_name='headphones',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='smartwatches',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Изображение'),
        ),
    ]
